version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    container_name: obsidian-couchdb
    restart: unless-stopped

    environment:
      # Set these in Coolify Environment Variables UI (more secure)
      # Or create .env file locally (DO NOT commit to GitHub)
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

    # Remove port mapping - Coolify will handle this via Traefik
    # ports:
    #   - "5984:5984"

    volumes:
      # Persistent data storage
      - couchdb-data:/opt/couchdb/data
      - couchdb-config:/opt/couchdb/etc/local.d
      - ./couchdb-config/local.ini:/opt/couchdb/etc/local.d/local.ini

    networks:
      - obsidian-network

    labels:
      # Traefik labels for Coolify proxy
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian-couchdb.rule=Host(`obsidian.umbryth.com`)"
      - "traefik.http.routers.obsidian-couchdb.entrypoints=websecure"
      - "traefik.http.routers.obsidian-couchdb.tls.certresolver=letsencrypt"
      - "traefik.http.services.obsidian-couchdb.loadbalancer.server.port=5984"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  couchdb-data:
    driver: local
  couchdb-config:
    driver: local

networks:
  obsidian-network:
    driver: bridge
